config/routes.rb
Rails.application.routes.draw do
  resources :genres

  resources :authors

  resources :line_items

  resources :carts

  resources :book_orders

  resources :users

  resources :book_exemplars

  resources :books

  get "login"=>"sessions#new", as: :login
  post "login"=>"sessions#create"
  patch "logout"=>"sessions#destroy", as: :logout

  root "books#index"

end

app/models/book_order.rb
class BookOrder < ActiveRecord::Base

  after_create :send_mail
  after_create :decrease_q
  belongs_to :cart, ->{includes(:line_items => :book).order(:created_at)}
  belongs_to :user
  # belongs_to :book_exemplar
  has_many :line_items, dependent: :destroy
  scope :ordering, -> {order(created_at: :desc)}

  # STATUSES=%w(Оформлен Подтверждён Отменён Доставляется Завершён) #0 1 2 3 4
  validates :cart, presence: true
  validates :user, presence: true
  validates :address, presence: true
  # validates :email, presence: true

  validate :check_cart

  def check_cart
    if cart && cart.line_items.blank?
      errors.add(:cart, "Корзина пуста!")
    end
  end

  def decrease_q
    # self.cart.line_items.book.update()
    cart.line_items.each do |t|
      if t.book.amount!=0
        t.book.update(amount: t.book.amount-t.quantity)
        # t.book.amount-=t.quantity
        # t.book.save
      else puts "Книг больше нет!"

      end
    end
  end




  def add_lineitems(cart)
    line_items=[]
    cart.line_items.each do |l_i|
      l_i.cart_id=nil
      line_items << l_i
    end
  end
  def send_mail
    BookOrderMailer.info_email(self).deliver_later
    true
  end

end

app/controllers/book_orders_controller.rb
class BookOrdersController < ApplicationController
  before_action :set_book_order, only: [:show, :edit, :update, :destroy]
  before_action :require_login
  # before_action :manager_permission, except: [:new, :create]

  # GET /book_order
  # GET /book_order.json
  def index
    if !@current_user.blank?
      if @current_user.role == 0
        @book_orders = BookOrder.where(user_id: @current_user.id).ordering.page(params[:page])
      else
        @book_orders = BookOrder.ordering.page(params[:page])
      end
    end
  end

  # GET /book_order/1
  # GET /book_order/1.json
  def show
  end

  # GET /book_order/new
  def new
    @book_order = BookOrder.new
  end

  # GET /book_order/1/edit
  def edit
  end

  # POST /book_order
  # POST /book_order.json
  def create
    @book_order = BookOrder.new(new_book_order_params)
    @book_order.cart = @cart
    @book_order.user = @current_user
    # @book_order.decrease_q
    @book_order.add_lineitems(@cart)
    if @book_order.save
      session.delete(:cart_id)
      redirect_to root_path, notice: 'Заказ оформлен.'
    else
      render :new
    end
  end

  # PATCH/PUT /book_order/1
  # PATCH/PUT /book_order/1.json
  def update
    respond_to do |format|
      if @book_order.update(book_order_params)
        format.html { redirect_to @book_order, notice: 'Заказ изменён.' }
        format.json { render :show, location: @book_order }
      else
        format.html { render :edit }
        format.json { render json: @book_order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /book_order/1
  # DELETE /book_order/1.json
  def destroy
    @book_order.destroy
    respond_to do |format|
      format.html { redirect_to book_orders_url, notice: 'Заказ удалён.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_book_order
    @book_order = BookOrder.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def book_order_params
    params.require(:book_order).permit(:cart_id, :user_id, :address, :comment)
  end

  def new_book_order_params
    params.require(:book_order).permit(:address, :comment)
  end
end

app/helpers/book_orders_helper.rb
module BookOrdersHelper

  def select_user(user, selected = nil)
    select_tag(user, options_for_select(
                     User.book_order('email').load.map{ |x| [x.email, x.id] } + [['', nil]], [selected]))
  end

  def select_book(name, selected = nil)
    select_tag(name, options_for_select(Book.order('name').load.map{ |x| [x.name, x.id] } + [['', nil]],[selected]))
  end

end

app/views/book_orders/_form.html.haml
= form_for @book_order do |f|
  =error_messages_for(@book_order)

  .field
    = f.label :cart
    = f.text_field :cart, class: 'form-control'
  .field
    = f.label :user
    = f.text_field :user, class: 'form-control'
  .field
    = f.label :address
    = f.text_area :address, class: 'form-control'
  .field
    = f.label :comment
    = f.text_area :comment, class: 'form-control'
  .actions
    = f.submit 'Сохранить', class: 'btn btn-primary'

app/views/book_orders/_show.html.haml
.page-header
  %h1 Список заказов

%table.table.table-bordered.table-hover.table-condensed
  %thead
    %tr
      %th Корзина
      %th Пользователь
      %th Адрес доставки
      %th Комментарий
      %th
      %th
      %th

  %tbody
    - @book_orders.each do |book_order|
      %tr
        %td= book_order.cart_id
        %td= book_order.user_id
        %td= book_order.address
        %td= book_order.comment
        %td= link_to 'Показать', book_order
        %td= link_to 'Редактировать', edit_book_order_path(book_order)
        %td= link_to 'Удалить', book_order, :method => :delete, :data => { :confirm => 'Вы уверены?' }

%br
= paginate @book_orders

app/views/book_orders/edit.html.haml
%h1 Редактирование заказа
= form_for @book_order do |ord|
  =error_messages_for(@book_order)
  -#= render 'form'
  .form-group
    = label_tag('book_order[user_id]', Book_order.human_attribute_name(:user_id))
    = select_user('book_order[user_id]', @book_order.user_id)
  .form-group
    =ord.label :comment
    =ord.text_field :comment, class: "form-control"
  .form-group
    =ord.label :address
    =ord.text_field :address, class: "form-control"

  .actions
    = ord.submit 'Сохранить'
= link_to 'Показать', @book_order
\|
= link_to 'Назад', book_orders_path

app/views/book_orders/index.html.haml
-#-if @current_user.try(:admin?)

-#.page-header
-#  <h2>Заказы</h2>

- if @current_user.blank?
  =redirect_to new_user_path, notice:"Вы не зарегестрированный пользователь"

- if !@current_user.blank?
  -if @current_user.try(:admin?)
    %h1 Заказы всех пользователей


    .row
      .list-group
        .list-group-item.active
          .row
            .col-md-1
              Корзина
            .col-md-2
              Пользователь
            .col-md-3
              Адрес
            .col-md-1
              Количество
            .col-md-2
              Дата
      .list-group
        - @book_orders.each do |item|
          .list-group-item
            .row
              .col-md-1
                #{item.cart.id}
              .col-md-2
                #{item.user.email}
                =link_to '',item.user, class:"fa fa-arrow-circle-right"
              .col-md-3
                #{item.address}
              .col-md-1
                #{item.cart.line_items.length}
              .col-md-2
                #{item.created_at.strftime("%d %b. %Y %H:%M")}
              -#%td= link_to 'Показать', book_order
              -#%td= link_to 'Редактировать', edit_book_order_path(book_order)
              -#%td= link_to 'Удалить', book_order, :method => :delete, :data => { :confirm => 'Вы уверены?' }

              -#.list-group-item
              -#.row.text-center
              .col-xs-1
                .button= link_to '', item, class: "btn btn-info btn-sm fa fa-eye", title: "Показать"
              .col-xs-1.col-md-1
                .button= link_to '', edit_book_order_path(item), class: "btn btn-warning btn-sm fa fa-pencil", title:"Редактировать"
              .col-xs-1
                .button= link_to '', item, :method => :delete, :data => { :confirm => 'Вы уверены?' }, class: "btn btn-danger btn-sm fa fa-trash", title: "Удалить"

  -if !@current_user.try(:admin?)
    %h1 Заказы

    .row
      .list-group
        .list-group-item.active
          .row
            .col-md-1
              Корзина
            .col-md-3
              Адрес
            .col-md-3
              Дата
      - @book_orders.each do |item|
        .list-group-item
          .row
            .col-md-1
              #{item.cart.id}
            .col-md-3
              #{item.address}
            .col-md-3
              #{item.created_at.strftime("%d %b. %Y %H:%M")}

            .col-xs-1
              .button= link_to '', item, class: "btn btn-info btn-sm fa fa-eye", title: "Показать"
%br
= paginate @book_orders



-#
-#- if !@current_user.blank?
-#  - if @current_user.role == 0
-#    %h1 Список заказов
-#  - else
-#    %h1 Заказы всех пользователей
-#
-#- if !@current_user.blank?
-#  - if BookOrder.where(user_id: @current_user.id).count == 0
-#    .alert.alert-info У Вас еще нет ни одного заказа
-#  - else
-#    %table.table.table-bordered.table-hover.table-condensed
-#      %thead
-#        %tr
-#          %th Корзина
-#          %th Пользователь
-#          %th Адрес
-#          %th Комментарий
-#          %th
-#          %th
-#          - if !@current_user.blank?
-#            - if @current_user.role!=0
-#              %th
-#
-#      %tbody
-#        - @book_orders.each do |book_order|
-#          %tr
-#            %td= book_order.cart.id
-#            %td= book_order.user.email
-#            %td= book_order.address
-#            %td= book_order.comment
-#            %td= book_order.created_at
-#            %td= link_to 'Показать', book_order
-#            %td= link_to 'Редактировать', edit_book_order_path(book_order)
-#            - if !@current_user.blank?
-#              - if @current_user.role!=0
-#                %td= link_to 'Удалить', book_order, :method => :delete, :data => { :confirm => 'Вы уверены?' }
-#%br
-#
-#= paginate @book_orders

-#===========================

-#
-#
-#.page-header
-#  <h2>Корзина</h2>
-#.row
-#  .list-group
-#    .list-group-item.active
-#      .row
-#        .col-md-3
-#          Название
-#        .col-md-3
-#          Количество
-#        .col-md-3
-#          Цена
-#        .col-md-3
-#          Сумма
-#  - @cart.line_items.each do |item|
-#    .list-group-item
-#      .row
-#        .col-md-3
-#          #{item.book.name}
-#        .col-md-3
-#          =link_to '',line_item_path(id:item.id,place:"line_items"), data:{method: :delete}, class:"btn btn-mini glyphicon glyphicon-minus"
-#          #{item.quantity}
-#          =link_to '',line_items_path(id:item.id,place:"line_items"),data:{method: :post}, class:"btn btn-mini glyphicon glyphicon-plus"
-#        .col-md-3
-#          #{item.price}
-#        .col-md-3
-#          #{item.quantity*item.price}
-#.row
-#  .col-md-4
-#    .list-group
-#      .list-group-item.active.glyphicon.glyphicon-list.li
-#        Итог:
-#      .list-group-item.glyphicon.glyphicon-info-sign.li
-#        Всего товарных позиций: #{@cart.line_items.length}
-#        .br
-#        .li
-#          Всего книг:
-#          #{@cart.line_items.sum("quantity")}
-#      .list-group-item.glyphicon.glyphicon-ruble
-#        Цена:
-#        #{number_to_currency(@cart.all_summ)}
-#
-#-#= link_to 'Редактировать', edit_cart_path(@cart), class: "btn btn-link"
-#= link_to 'Очистить корзину', @cart, data:{method: :delete, confirm: "Вы уверены?"}, class: "btn btn-primary"
-#\|
-#= link_to 'Вернуться к выбору книг', books_path, class: "btn btn-info"
-#\|
-#= link_to 'Оформить заказ', new_book_order_path, class: "btn btn-danger"

app/views/book_orders/new.html.haml
.page-header
  %h1 Оформление заказа
= form_for @book_order do |f|
  =error_messages_for(@book_order)
  .form-group
    =f.label :address
    =f.text_area :address, class: "form-control", rows: 3
  .form-group
    =f.label :comment
    =f.text_area :comment, class: "form-control", rows: 3

  .actions=f.submit nil, class: "btn btn-primary"







  -#.page-header
-#  %h1 Новый заказ
-#=render 'form'
-#
-#=form_for @book_order do |f|
-#  =error_messages_for @book_order

  -#.form-group.col-md-4
  -#  =f.label :address
  -#  =f.text_area :address, class: 'form-control', rows: 1
  -#  .row
  -#  %br
  -#    .actions=f.submit nil, class: 'btn btn-primary'

    -#= image_tag bookd.image.url(:medium),size:"173x232", alt: bookd.name, class: 'img-responsive'
    -#-if !@book.document.blank?
    -#  =link_to "Download Now", @book.document, :class => "btn btn-large btn-danger"


    = link_to 'Назад', book_orders_path

app/views/book_orders/show.html.haml
%p#notice= notice

%p
  %b Корзина:
  = @book_order.cart.id
%p
  %b Пользователь:
  = @book_order.user.email
  = link_to @book_order.user, class: "btn btn-link" do
    =fa_icon "arrow-circle-right"

%p
  %b Адрес доставки:
  = @book_order.address
%p
  %b Комментарий:
  = @book_order.comment

%p
  %b Список товаров:
  .row
    - @book_order.cart.line_items.each do |item|
      .col-md-2
        .list-group.ul
          .list-group-item.active.li
            .span.badge=item.quantity
            = item.book.name
            = link_to item.book, class: "btn btn-link"do
              =fa_icon "arrow-circle-right"
          .list-group-item.li
            =item.book.author.name
          .list-group-item.li
            .span.badge= fa_icon "ruble"
            =number_to_currency(item.price*item.quantity,
              separator: ",", delimiter: "", format: "%n")
          .list-group-item.li
            .span-badge=item.created_at.strftime("%d %b. %Y %H:%M")

          -#.list-group-item
          -#  =link_to "Download Now", @book.document, :class => "btn btn-large btn-danger"
-if @current_user.try(:admin?)
  = link_to 'Изменить', edit_book_order_path(@book_order)
  |
= link_to 'Назад', book_orders_path, class: 'btn btn-primary'

-#
-#%p
-#  %b Корзина:
-#  = @order.cart.id
-#%p
-#  %b Пользователь:
-#  = link_to "#{@order.user.email}", user_path(id: @order.user.id)
-#%p
-#  %b Адрес:
-#  = @order.address
-#%p
-#  %b Статус:
-#  = @statuses[@order.status-1]
-#%p
-#  %b Комментарий:
-#  = @order.comment
-#%p
-#  %b Список товаров:
-#  .row
-#    - @order.cart.line_items.each do |item|
-#      .col-md-3
-#        .list-group
-#          .list-group-item.active
-#            .fa.fa-pencil.li
-#              #{item.product.name}
-#          .list-group-item
-#            .fa.fa-info-circle.li
-#              #{item.product.description}
-#          .list-group-item
-#            .fa.fa-ruble.li
-#              #{number_to_currency(item.price*item.quantity, separator: ",", delimiter: "", format: "%n")}
-#          .list-group-item
-#            .fa.fa-tags.li
-#              #{item.quantity} шт
-#          -#.list-group-item
-#          -#  .fa.fa-download.li
-#          -#    #{number_to_human(item.product.weight*item.quantity, units: {unit: "г", thousand: "кг"})}
-#          .list-group-item
-#            .fa.fa-remove.li
-#            =link_to 'Удалить', item, method: :delete, data: {:confirm => 'Вы уверены?'}
-#.br
-#=link_to 'Добавить другую книгу', products_path(cart_id: @order.cart.id, user_id: @order.user.id), class: "btn btn-link"
-#.br
-#= link_to 'Редактировать', edit_order_path(@order)
-#\|
-#= link_to 'Назад', orders_path