config/routes.rb
Rails.application.routes.draw do
  resources :genres

  resources :authors

  resources :line_items

  resources :carts

  resources :book_orders

  resources :users

  resources :book_exemplars

  resources :books

  get "login"=>"sessions#new", as: :login
  post "login"=>"sessions#create"
  patch "logout"=>"sessions#destroy", as: :logout

  root "books#index"

end

app/models/book.rb
class Book < ActiveRecord::Base
  has_attached_file :image, styles:{medium: "300x300", thumb:"100x100"}
  has_attached_file :document #, styles: {thumbnail: "60x60"}
  has_many :line_items, dependent: :nullify
  belongs_to :genre
  belongs_to :author, class_name: 'Author'

  before_destroy :can_destroy?

  validates_attachment :document, content_type: { content_type: "application/pdf" }
  #validates_attachment :document, content_type: {content_type:/\A\//}
  validates_attachment :image, content_type: {content_type: /\Aimage\/.*\z/}
  # validates :genre, presence: true
  validates :amount, numericality:{only_integer: true}
  validates :name, presence: true, length: {maximum: 200}
  validates :price, presence: true, numericality:{greater_than: 0}

#  validates :weight, numericality:{only_integer: true, greater_than: 0}, allow_blank: true
#   scope :full, -> { includes(:genre, :author) }
#   attr_reader :author_tokens

  def self.manage?(u)
    u.try(:admin?)
  end
  #
  # def author_tokens=(val)
  #   self.author_ids=val.split(',')
  # end

  def can_destroy?
    line_items.blank?
  end

  def can_sell?
    amount>0
  end

  # def download
  #   file_name = params["file_id"] + ".pdf" data = open("s3.amazonaws.com/#{ENV['S3_BUCKET_NAME']}/#{file_name}") send_data data.read, :filename => file_name, :type => "application/pdf", :disposition => 'attachment', :stream => 'true', :buffer_size => '4096'
  # end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:show, :edit, :update, :destroy]

  # GET /books
  # GET /books.json
  def index
    @books = Book.page(params[:page])
    # data = open(params[:file])
    # send_data data, :filename => params[:document]
  end

  # GET /books/1
  # GET /books/1.json
  def show

    def pdf
      pdf_filename = File.join(Rails.root, "app/assets/docs/doc1.pdf")
      send_file(pdf_filename, :filename => "your_document.pdf", :type => "application/pdf")
    end

  end

  # GET /books/new
  def new
    if !@current_user.try(:admin?)
      redirect_to new_user_path, notice:"Вы не админинстратор"
    else
      @book = Book.new
    end
  end

  # GET /books/1/edit
  def edit
    if !@current_user.try(:admin?)
      redirect_to new_user_path, notice:"Вы не админинстратор"
    end
  end

  # POST /books
  # POST /books.json
  def create
    @book = Book.new(book_params)
    @book.document = params[:book][:document]
    if @book.save
      redirect_to @book
    else
      render :new
    end
  end


  # PATCH/PUT /books/1
  # PATCH/PUT /books/1.json
  def update
    if @book.update(book_params)
      redirect_to @book, notice: 'Книга успешно изменена.'
    else
      render :edit
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book.destroy
    redirect_to books_url, notice: 'Книга успешно удалена.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    def manager_permission
      render_error unless Book.manage?(@current_user)
    end
    # Never trust parameters from the scary internet, only allow the white list through.
    def book_params
      params.require(:book).permit(:name, :amount, :year, :author_id, :pages_amount, :genre_id, :isbn, :udc, :lbc, :image, :description, :price, :document)
    end
end

app/helpers/books_helper.rb
module BooksHelper

  # def d_amount(book)
  #   @book=book
  #   self.amount-=1
  #   self.save
  # end
  require 'pdf-reader'
  require 'open-uri'
  def read_book
    io     = open('app/assets/docs/doc1.pdf')
    reader = PDF::Reader.new(io)
    puts reader.info
  end

  def download_pdf
    book = Book.find(params[:id])
    send_data book.document,
              filename: "#{book.name}.pdf",
              type: "application/pdf"
  end


end

app/views/books/_book.html.haml
=link_to book, class: 'list-group-item' do
  .media
    -if book.image.blank?
      .media-left=image_tag ("blank.png"), height:"150", style: "display: block; margin: 0px auto;", alt: book.name, class: 'media-object'
    -if !book.image.blank?
      .media-left=image_tag book.image.url, height:"150", style: "display: block; margin: 0px auto;", alt: book.name, class: 'media-object'


    -#-if !book.image.blank?
    -#  = link_to book, class: "form-group" do
    -#    .media-left=image_tag book.image.url(:small), alt: book.name, class: 'media-object'
    -#-else
    -#  = link_to book, class: "form-group" do
    -#    .media-left=image_tag ("blank.png"),src: root_path, class: 'media-object'
    .media-body
      %h4.media-heading
        =book.name
      %i
        =book.genre.name

app/views/books/_form.html.haml
= form_for @book do |f|
  - if @book.errors.any?
    #error_explanation
      %h2
        = pluralize(@book.errors.count, "error")
        prohibited this book from being saved:
      %ul
        - @book.errors.full_messages.each do |message|
          %li= message
  .field
    = f.label :name
    %br/
    = f.text_field :name, class: 'form-control'
  .field
    = f.label :amount
    %br/
    = f.number_field :amount, class: 'form-control'
  .field
    = f.label :year
    %br/
    -#= f.date_select :year, :discard_year => true
    = f.text_field :year, class: 'form-control'
  .field
    = f.label :pages_amount
    %br/
    = f.number_field :pages_amount, class: 'form-control'
  .field
    =f.label "Жанр"
    %br/
    =f.select :genre_id, Genre.ordering.map{|c| [c.name,c.id]},{}, class: 'form-control'

  .field
    =f.label "Автор"
    %br/
    =f.select :author_id, Author.ordering.map{|c| [c.name,c.id]},{}, class: 'form-control'
    -#=f.text_field :author_id, data: {tokeninput:  authors_path(format: :json),
    -#    pre: [@book.author].compact.to_json, limit: 1}
  .field
    = f.label :isbn
    %br/
    = f.text_field :isbn, class: 'form-control'
  .field
    = f.label :udc
    %br/
    = f.text_field :udc, class: 'form-control'
  .field
    = f.label :lbc
    %br/
    = f.text_field :lbc, class: 'form-control'
  .field
    = f.label "Цена"
    %br/
    = f.number_field :price, class: 'form-control'
  .field
    = f.label "Описание"
    %br/
    = f.text_area :description, class: 'form-control'
  -if !@book.image.blank?
    = image_tag @book.image.url(:medium),size:"173x232", alt: @book.name, class: 'img-responsive'

  .field
    = f.label :image
    %br/
    = f.file_field :image
  -#.field
  -#  = f.label :document
  -#  %br/
  -#  = f.file_field :document
  %p

  .actions=f.submit 'Сохранить', class: "btn btn-primary"
%p

app/views/books/edit.html.haml
%h1 Изменение книги
= render 'form'
-#= link_to 'Показать', @book
-#|
-#= link_to 'Назад', books_path

app/views/books/index.html.haml
-#%p#notice= notice
-#%h1 Книги
-#%table
-#  %thead
-#    %tr
-#      %th Название
-#      %th Количество
-#      %th Дата создания
-#      %th Автор
-#      %th Количество страниц
-#      %th Isbn
-#      %th Udc
-#      %th Lbc
-#      %th Цена
-#      %th{:colspan => "3"}
-#  %tbody
-#    - @books.each do |book|
-#      %tr
-#        %td= book.name
-#        %td= book.amount
-#        %td= book.year
-#        %td= book.author
-#        %td= book.pages_amount
-#        %td= book.isbn
-#        %td= book.udc
-#        %td= book.lbc
-#        %td= book.price
-#        %td= link_to 'Показать', book
-#        %td= link_to 'Изменить', edit_book_path(book)
-#        %td= link_to 'Удалить', book, method: :delete, data: { confirm: 'Are you sure?' }
-#%br/
-#= link_to 'Новая Книга', new_book_path
-#= link_to 'В корзину', line_items_path(book_exemplar_id: book_exemplar.id), data:{method: :post, remote: :true}, class:"btn btn-danger glyphicon glyphicon-plus"
-#-if @book.image?
-#  =link_to @book.image.url do
-#    =image_tag @book.image.url(:thumb)
-#=image_tag @film.cover.url(:medium), alt: @film.name, class: 'img-responsive'

.page-header
  %h1 Книги
.container
  -@books.each do |bookd|
    -#.col-md-3
    -#  .list-group
    -#    .list-group-item
    -#
    -#      .book
    -#      -if !bookd.image.blank?
    -#        = image_tag bookd.image.url(:medium), alt: bookd.name, class: 'img-responsive'
    .col-md-4
      .list-group
        .list-group-item
          -if !bookd.image.blank?
            = link_to bookd, class: "form-group" do
              =image_tag bookd.image.url(:medium), height:"265", style: "display: block; margin: 0px auto;", alt: bookd.name, class: "thumb"
          -else
            = link_to bookd, class: "form-group" do
              =image_tag ("blank.png"),src: root_path, height:"265", style: "display: block; margin: 0px auto;"#, data: {toggle: "collapse", target:"#menu"}
        .list-group-item
          %h4
            = link_to "#{bookd.name}", bookd, style: "color: black"

        .list-group-item
          Автор
          .badge
            =bookd.author.name
        .list-group-item
          Жанр
          .badge
            =bookd.genre.name
        .list-group-item
          Цена:
          .badge
            =number_to_currency(bookd.price)

        .list-group-item
          .row.text-center
            .col-xs-3.pull-left
              .button= link_to '', line_items_path(book_id: bookd.id), data:{method: :post, remote: :true}, class:"btn btn-success btn-lg fa fa-cart-plus", title: "Добавить в корзину"
            -if @current_user.try(:admin?)
              .col-xs-3
                .button= link_to '', bookd, class: "btn btn-info btn-lg fa fa-eye", title: "Показать"
            -if @current_user.nil? or !@current_user.nil? and  !@current_user.try(:admin?)
              .col-xs-3.pull-right
                .button= link_to '', bookd, class: "btn btn-info btn-lg fa fa-eye", title: "Показать"
            -if @current_user.try(:admin?)
              .col-xs-3.col-md-3
                .button= link_to '', edit_book_path(bookd), class: "btn btn-warning btn-lg fa fa-pencil", title:"Редактировать"
              .col-xs-3.pull-right
                .button= link_to '', bookd, :method => :delete, :data => { :confirm => 'Вы уверены?' }, class: "btn btn-danger btn-lg  fa fa-trash", title: "Удалить"

          -#%table
          -#  %tr
          -#    .button-group-gorisontal
          -#      %td
          -#        .button= link_to '', line_items_path(book_id: bookd.id), data:{method: :post, remote: :true}, class:"btn btn-success glyphicon glyphicon-plus", title: "Добавить в корзину"
          -#      %td
          -#        .button= link_to '', bookd, class: "btn btn-info glyphicon glyphicon-search", title: "Показать"
          -#      %td
          -#        .button= link_to '', edit_book_path(bookd), class: "btn btn-warning glyphicon glyphicon-pencil", title:"Редактировать"
          -#      %td
          -#        .button= link_to '', bookd, :method => :delete, :data => { :confirm => 'Вы уверены?' }, class: "btn btn-danger glyphicon glyphicon-trash", title: "Удалить"
-if @current_user.try(:admin?)
  .br
  = link_to ' Новая Книга', new_book_path, class: "btn btn-primary fa fa-plus"

.br
= paginate @books


-#
-#
-#      .list-group-item
-#        .row.text-center
-#          .col-xs-3.pull-left
-#            .button= link_to '', line_items_path(book_id: bookd.id), data:{method: :post, remote: :true}, class:"btn btn-success glyphicon glyphicon-plus", title: "Добавить в корзину"
-#      -if !@current_user.nil?
-#        -if @current_user.admin?
-#          -#%div{class: "col-xs-#{@current_user.admin? ? 3 : 6}"}
-#          %div{class: "col-xs-#{@current_user.admin? ? 3 : 6}"}
-#            .button= link_to '', bookd, class: "btn btn-info glyphicon glyphicon-search", title: "Показать"
-#          -if !@current_user.nil?
-#            -if @current_user.admin?
-#              .col-xs-3.col-md-3
-#                .button= link_to '', edit_book_path(bookd), class: "btn btn-warning glyphicon glyphicon-pencil", title:"Редактировать"
-#          .col-xs-3.pull-right
-#            .button= link_to '', bookd, :method => :delete, :data => { :confirm => 'Вы уверены?' }, class: "btn btn-danger glyphicon glyphicon-trash", title: "Удалить"
-#
-#
-#
-#.list-group-item
-#  .row.text-center
-#    .col-xs-3.pull-left
-#      .button= link_to '', line_items_path(book_id: bookd.id), data:{method: :post, remote: :true}, class:"btn btn-success glyphicon glyphicon-plus", title: "Добавить в корзину"
-#    %div{class: "col-xs-#{@current_user.admin? ? 3 : 6}"}
-#      .button= link_to '', bookd, class: "btn btn-info glyphicon glyphicon-search", title: "Показать"
-#    -if @current_user.admin?
-#      .col-xs-3.col-md-3
-#        .button= link_to '', edit_book_path(bookd), class: "btn btn-warning glyphicon glyphicon-pencil", title:"Редактировать"
-#    .col-xs-3.pull-right
-#      .button= link_to '', bookd, :method => :delete, :data => { :confirm => 'Вы уверены?' }, class: "btn btn-danger glyphicon glyphicon-trash", title: "Удалить"

app/views/books/new.html.haml
%h1 Новая Книга
= render 'form'
= link_to 'Назад', books_path, class: 'btn btn-primary'

app/views/books/show.html.haml
-require 'open-uri'
-require 'pdf/reader'
.br
.page-header
  .h1=@book.name

-#-if @book.image?
-#  =link_to @book.image.url do
-#    =image_tag @book.image.url(:thumb)
    -#=image_tag @book.image, alt: @book.name


-if !@book.image.blank?
  = image_tag @book.image.url(:medium), height:"265"#, alt: @book.name, class: 'img-responsive'
-else
  =image_tag ("blank.png"),src: root_path, height:"265", data: {toggle: "collapse", target:"#menu"}#, alt: @book.name, class: 'img-responsive'


-#.row
-#  .pull-right.col-md-3{style: "white-space: nowrap"}
-#    .glyphicon.glyphicon-chevron-right
-#    -@sum,@sum2=0,0;@cart.line_items.each{|itm| @sum+=itm.quantity;@sum2+=itm.price*itm.quantity}
-#    = link_to "В вашей корзине #{@sum} #{Russian.p(@sum,'товар','товара','товаров')}. Общая цена: #{number_to_currency(@sum2, separator: ",", delimiter: "", unit: "₽", format: "%n %u")}", @cart, class: "btn btn-danger", :style => "white-space:normal; width: 216px;"

-#t.string :name, null: false
-#t.integer :amount
-#t.date :year
-#t.string :author, null: false
-#t.integer :pages_amount
-#t.string :isbn
-#t.string :udc
-#t.string :lbc
-#t.integer :price
-#t.text :description
-#t.attachment :document
%p
%p
  %b Название:
  = @book.name
%p
  %b Автор:
  =link_to @book.author.name, @book.author
  -#=render 'authors/author', author: @book.author
%p
  %b Количество:
  = @book.amount
%p
  %b Год:
  = @book.year
%p
  %b Количество страниц:
  = @book.pages_amount
%p
  %b Жанр
  -#=Book.human_attribute_name(:genre)
  =link_to @book.genre.name,@book.genre
%p
  %b ISBN:
  = @book.isbn
%p
  %b UDC:
  = @book.udc
%p
  %b LBC:
  = @book.lbc
%p
  %b Описание:
  = @book.description
%p
  %b Цена:
  = number_to_currency(@book.price)

-#%p
-#  %b Book:
-#  = @book.name
-#  = link_to @book.document.url
-#  =fa_icon "arrow-circle-right"

-#%p
-#  = link_to @book.document, class: "btn btn-link" do
-#    =fa_icon "arrow-circle-right"

%p

-a=@cart.line_items.where("book_id= ?",@book.id)
-if !a.blank?
  -b=a[0]
  %b В вашей корзине:
  =link_to '',line_item_path(id:b.id,place: "show"), data:{method: :delete}, class:"btn btn-mini glyphicon glyphicon-minus"
  #{b.quantity}
  =link_to '',line_items_path(id:b.id,place: "show"),data:{:method => :post}, class:"btn btn-mini glyphicon glyphicon-plus"
%p
-#%p
-#-if @current_user.admin?
-#  =  @book.document.url(:medium), alt: @book.name, class: 'img-responsive'

= link_to line_items_path(book_id: @book.id,book:@book), data:{method: :post}, class: "btn btn-success" do
  =fa_icon "cart-plus"
  Добавить в корзину
\|
= link_to line_items_path, class: "btn btn-info" do
  =fa_icon "shopping-cart"
  Перейти к корзине
-if @current_user.try(:admin?)
  \|
  = link_to edit_book_path(@book), class: "btn btn-warning" do
    =fa_icon "pencil"
    Редактировать
\|
= link_to books_path, class: "btn btn-primary" do
  =fa_icon "reply"
  Вернуться к списку книг
%p