config/routes.rb
Rails.application.routes.draw do
  resources :genres

  resources :authors

  resources :line_items

  resources :carts

  resources :book_orders

  resources :users

  resources :book_exemplars

  resources :books

  get "login"=>"sessions#new", as: :login
  post "login"=>"sessions#create"
  patch "logout"=>"sessions#destroy", as: :logout

  root "books#index"

end

app/models/cart.rb
class Cart < ActiveRecord::Base
  has_many :line_items, ->{includes(:book).order(:created_at)}, dependent: :destroy
  has_one :book_order, dependent: :destroy
  def add_item(p)
    line_item = line_items.where(book_id: p.id).first
    unless line_item
      line_item = self.line_items.build(book: p, quantity: 0, price: p.price)
    end
    line_item.quantity+=1
    line_item.save
  end

  def total_line_items
    line_items.sum(:quantity)
  end

  def total_amount
    self.line_items.sum("quantity*line_items.price")
  end

  def all_summ
    a=0
    self.line_items.each{|item| a+=item.price * item.quantity}
    a
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  # GET /carts
  # GET /carts.json
  def index
    @carts = Cart.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @carts }
    end
  end

  # GET /carts/1
  # GET /carts/1.json
  def show
  end

  # GET /carts/new
  def new
    @cart = Cart.new
  end

  # GET /carts/1/edit
  def edit
    if !@current_user.try(:admin?)
      redirect_to new_user_path, notice:"Вы не админинстратор"
    end
  end

  # POST /carts
  # POST /carts.json
  def create
    @cart = Cart.new(cart_params)

    respond_to do |format|
      if @cart.save
        format.html { redirect_to @cart, notice: 'Корзина создана.' }
        format.json { render :show, status: :created, location: @cart }
      else
        format.html { render :new }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /carts/1
  # PATCH/PUT /carts/1.json
  def update
    respond_to do |format|
      if @cart.update(cart_params)
        format.html { redirect_to @cart, notice: 'Корзина изменена.' }
        format.json { render :show, status: :ok, location: @cart }
      else
        format.html { render :edit }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carts/1
  # DELETE /carts/1.json
  def destroy
    @cart.destroy
    redirect_to root_path, notice: 'Корзина очищена.'
  end

  private
  # Use callbacks to share common setup or constraints between actions.

  # Never trust parameters from the scary internet, only allow the white list through.
  def cart_params
    params[:cart]
  end
end

app/helpers/carts_helper.rb
module CartsHelper
  def show_cart(cart)
    #render 'carts/cart', cart:cart
    if cart.line_items.blank?
      text="Ваша корзина пуста"
      content_tag(:div,text,class:"alert alert-danger",id:"my_cart")
    else

      text="В корзине #{cart.total_line_items} #{Russian.p(cart.total_line_items,'товар','товара','товаров')} на сумму #{number_to_currency(cart.total_amount)}"

      content_tag(:div,text,class:"alert alert-danger",id:"my_cart")
    end
  end

  def upd_cart(cart)
    "В корзине #{cart.total_line_items} #{Russian.p(cart.total_line_items,'товар','товара','товаров')} на сумму #{number_to_currency(cart.total_amount)}"
  end
end

app/views/carts/_cart.html.haml
#cart_info
  -if cart
    -if cart.line_items.blank?
      .alert.alert-info
        В корзине
        =Russian.p(cart.total_line_items,'товар','товара','товаров')
        на сумму
        =number_to_currency(cart.total_amount)

app/views/carts/_form.html.haml
= form_for @cart do |f|
  - if @cart.errors.any?
    #error_explanation
      %h2= "#{pluralize(@cart.errors.count, "error")} prohibited this cart from being saved:"
      %ul
        - @cart.errors.full_messages.each do |msg|
          %li= msg
          #link_to - оформить заказ

  .actions
    = f.submit 'Сохранить'

app/views/carts/edit.html.haml
%h1 Изменение корзины

-if @current_user.try(:admin?)
  = render 'form'

  = link_to 'Посмотреть', @cart
  \|
  = link_to 'Назад', carts_path
-else
  = render login_path

app/views/carts/index.html.haml
%h1 Корзина



%table
  %thead
    %tr
      %th
      %th
      %th

  %tbody
    - @carts.each do |cart|
      %tr

        %td= link_to 'Показать', cart, class: "btn btn-primary fa fa-connectdevelop"
        %td= link_to 'Редактировать', edit_cart_path(cart), class: "btn btn-primary fa fa-connectdevelop"
        %td= link_to 'Удалить', cart, :method => :delete, :data => { :confirm => 'Вы уверены?' }, class: "btn btn-primary fa fa-connectdevelop"

%br

= link_to 'Новая корзина', new_cart_path, class: "btn btn-primary fa fa-plus"

app/views/carts/new.html.haml
%h1 Новая корзина

= render 'form'

= link_to 'Назад', carts_path

app/views/carts/show.html.haml
-#%p#notice= notice
-#%h1 Listing Line Items
-#%table
-#  %thead
-#    %tr
-#      %th Количество
-#      %th Цена
-#      %th Корзина
-#      %th Эеземпляр книги
-#      %th{:colspan => "3"}
-#  %tbody
-#    - @line_items.each do |line_item|
-#      %tr
-#        %td= line_item.quantity
-#        %td= line_item.price
-#        %td= line_item.Cart
-#        %td= line_item.Book_exemplar
-#        %td= link_to 'Show', line_item
-#        %td= link_to 'Edit', edit_line_item_path(line_item)
-#        %td= link_to 'Destroy', line_item, method: :delete, data: { confirm: 'Are you sure?' }
-#%br/
-#= link_to 'New Line item', new_line_item_path

.page-header
  <h2>Корзина</h2>
.row
  .list-group
    .list-group-item.active
      .row
        .col-md-3
          Название
        .col-md-3
          Количество
        .col-md-3
          Цена
        .col-md-3
          Сумма
  .list-group
    - @cart.line_items.each do |item|
      .list-group-item
        .row
          .col-md-3
            #{item.book.name}
          .col-md-3
            =link_to '',line_item_path(id:item.id,place:"line_items"), data:{method: :delete}, class:"btn btn-mini glyphicon glyphicon-minus"
            #{item.quantity}
            =link_to '',line_items_path(id:item.id,place:"line_items"),data:{method: :post}, class:"btn btn-mini glyphicon glyphicon-plus"
          .col-md-3
            #{item.price}
          .col-md-3
            #{item.quantity*item.price}
%p
.row
  .col-md-4
    .list-group
      .list-group-item.active.glyphicon.glyphicon-list.li
        Итог:
      .list-group-item.glyphicon.glyphicon-info-sign.li
        Всего товарных позиций: #{@cart.line_items.length}
        .br
        .li
          Всего книг:
          #{@cart.line_items.sum("quantity")}
      .list-group-item.glyphicon.glyphicon-ruble
        Цена:
        #{number_to_currency(@cart.all_summ)}

-#= link_to 'Редактировать', edit_cart_path(@cart), class: "btn btn-link"
= link_to 'Очистить корзину', @cart, data:{method: :delete, confirm: "Вы уверены?"}, class: "btn btn-primary"
\|
= link_to 'Вернуться к выбору книг', books_path, class: "btn btn-info"
\|
= link_to 'Оформить заказ', new_book_order_path, class: "btn btn-danger"
%p