config/routes.rb
Rails.application.routes.draw do
  resources :genres

  resources :authors

  resources :line_items

  resources :carts

  resources :book_orders

  resources :users

  resources :book_exemplars

  resources :books

  get "login"=>"sessions#new", as: :login
  post "login"=>"sessions#create"
  patch "logout"=>"sessions#destroy", as: :logout

  root "books#index"

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  # rescue_from ActiveRecord::RecordNotFound, with: :record_not_found


  before_action :set_locale
  before_action :set_cart_
  before_action :set_current_user

  protect_from_forgery with: :exception

  def set_locale
    I18n.locale = params[:locale] || I18n.default_locale
  end

  private

  def record_not_found
    render plain:"404 Not Found", status: 404
  end

  def set_cart_
    @cart = Cart.find(session[:cart_id])
  rescue ActiveRecord::RecordNotFound
    @cart = Cart.create
    session[:cart_id] = @cart.id
  end

  def set_current_user
    if session[:user_id].present?
      @current_user=User.find(session[:user_id])
    end
  end

  def require_login
    if !@current_user
      flash[:danger]="Требуется авторизация"
      redirect_to login_path
    end
  end

  def manager_permission
    unless @current_user.try(:moderator?)
      flash[:danger]="Недостаточно прав"
      redirect_to login_path
    end
  end

  def admin_permission
    unless @current_user.try(:admin?)
      flash[:danger]="Недостаточно прав"
      redirect_to login_path
    end
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
  def error_messages_for(object)
    render "error_messages", object: object
  end
end

app/views/application/_error_messages.html.haml
-if object.errors.any?
  .panel.panel-danger
    .panel-heading При сохранении произошли ошибки!
  .panel-body
    %ul
      - object.errors.full_messages.each do |msg|
        %li=msg

app/views/application/_flash_messages.html.haml
-flash.each do |key,val|
  .alert{class: "alert-#{key}"}=val

app/views/application/_navbar.html.haml
%nav.navbar.navbar-inverse
  .container
    .navbar-header
      .navbar-brand
        .pull-right.collapse.navbar-collapse
          =image_tag ("logo_5.png"),src: root_path, size:"25x25", data: {toggle: "collapse", target:"#menu"}

      =link_to ?#, class: "navbar-toggle collapsed", data: {toggle: "collapse", target:"#menu"} do
        =fa_icon 'bars'
      =link_to "Библиотека", root_path, class: "navbar-brand"#, "logo_5.png"
    #menu.collapse.navbar-collapse
      %ul.nav.navbar-nav
        %li= link_to "Все книги", books_path
        %li= link_to "Корзина", line_items_path
        %li=link_to "Авторы", authors_path
        %li=link_to "Жанры", genres_path



      %ul.nav.navbar-nav.navbar-right
        -if @current_user.try(:admin?)
          %li=link_to 'Пользователи', users_path
        -if @current_user
          %li.dropdown
            =link_to ?#, class: 'dropdown-toggle', data: {toggle: 'dropdown'} do
              =@current_user.email
              =fa_icon 'angle-down'
            %ul.dropdown-menu
              -#%li=link_to "Корзина", line_items_path
              -#-#%li=link_to "Избранное", @electee
              %li=link_to "Пользователь", @current_user
              %li=link_to "Заказы", book_orders_path
              %li=link_to 'Выход', logout_path, data:{method: :patch}
        -else
          %li=link_to 'Регистрация', new_user_path
          %li=link_to 'Вход', login_path

      -#
      -#
      -#%ul.nav.navbar-nav.navbar-right
      -#  -if @current_user.blank?
      -#    %li= link_to "Регистрация", new_user_path
      -#    %li= link_to "Войти", login_path
      -#  -elsif !@current_user.blank?
      -#    %li
      -#      = link_to "#{@current_user.email}", @current_user
      -#    -if  @current_user.admin?
      -#      %li= link_to "Пользователи", users_path

            -#%span.navbar-text=@current_user.email, user
        -#
        -#-if @current_user.blank?
        -#  -if  @current_user.admin?
        -#    %li= link_to "Пользователи", users_path

          %li
            = link_to "Выйти", logout_path, data:{method: :patch}